<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Font\iconfont.ttf" />
    <None Remove="Images\login_backImg.png" />
    <None Remove="Images\logo.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Font\iconfont.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\login_backImg.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\logo.png" />
  </ItemGroup>

</Project>
